### ISSUE TITLE
Alternative to UnoJoy?

### ISSUE THREAD

**Issue by cgten-uk** [JRomainG/Driving-Force-Shifter-USB-Adapter#1]
It looks like UnoJoy is no longer being maintained, and I'm having trouble flashing the firmware to my Arduino in order to use the shifter.  Are there any alternatives that can be used instead?

**Comment by JRomainG** [comment]
I guess an alternative is to use the [ArduinoJoystickLibrary](https://github.com/MHeironimus/ArduinoJoystickLibrary) if it is compatible with your Arduino board. I have created a [separate branch using this library](https://github.com/JRomainG/Driving-Force-Shifter-USB-Adapter/tree/ArduinoJoystickLibrary) if you want to check it out, though I do not have the hardware handy so I haven't tested it

You can also checkout the [AMStudio project on Github](https://github.com/AM-STUDIO/LOGITECH_USB_ADAPTER) which uses the `ArduinoJoystickLibrary` as well

**Comment by cgten-uk** [comment]
I'm just using an UNO R3.  I'm going to try out your branch when I get home tomorrow and let you know how I get on.
I'm guessing that since I'm using an UNO though, it might not work as a HID.  Do I need to buy a Leonardo then?

**Comment by JRomainG** [comment]
Considering you have an Arduino Uno, I don't think the `ArduinoJoystickLibrary` will work (or not easily at least, the wiki seems to mention [HoodLoader2](https://github.com/NicoHood/HoodLoader2) as an option). You could try with a Leonardo board which is supported, but before that perhaps trying to debug your issue with flashing the software on your existing board can be worth it.
Do you have any more details about what you have been struggling with?

**Comment by cgten-uk** [comment]
The issue has actually been with Java, at least I think it's either Java or the batch script not looking in the right place for the JVM (issue here https://github.com/AlanChatham/UnoJoy/issues/6).  I spent a good deal of time getting it to work, and other Java apps seem to work just fine, so I gave up.  I'm only using an UNO because that's what I happen to have laying around at the moment.

I may have access to an Arduino Micro, which I'd prefer to a Leonardo for space reasons.  I want to install the board inside the shifter housing and have a USB connection out the back.  I'll see how that goes using the ArduinoJoysickLibrary and feedback asap.

**Comment by cgten-uk** [comment]
Just tested this on a Pro Micro and aside from the gears being offset by 1, (gear 1 = button 2, gear 2 = button 3... etc), it's all working great.

**Comment by JRomainG** [comment]
Thanks for the update!
The gear numbers are indeed offset by 1 because there is an option for the "neutral" position to register as a gear (gear 0)
Should I consider this issue closed then?

**Comment by cgten-uk** [comment]
That makes sense.  Closing this issue now then!
