### ISSUE TITLE
Arduino UNO DFU mode

### ISSUE THREAD

**Issue by nyox2stupid** [JRomainG/Driving-Force-Shifter-USB-Adapter#3]
Hey, im pretty new to Arduino, and I cant put mine in DFU mode. There are almost no tutorials for it on the web. When I short the pins, one of the LED's blinks a few times and nothing happens. Thanks for help in advance

**Comment by JRomainG** [comment]
Sorry for the late reply.
Depending on the version of the Arduino UNO that you have, you might need to short other pins as [explained here](https://support.arduino.cc/hc/en-us/articles/4410804625682).
Alternatively, I think [this video](https://www.youtube.com/watch?v=E8XyRwXQr8Q) shows rather clearly how to set your Arduino into DFU mode.
I hope this helps!

**Comment by JRomainG** [comment]
As there has been no comment on this issue for a while, I'll go ahead and close it
